name: t1

on:
  workflow_dispatch:
    
jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
       - name: Checkout GTA5OnlineLua Sources
         uses: actions/checkout@v3
         with:
              path: GTA5OnlineLua
              submodules: recursive
              
       - name: git pull6
         run: |
          cd GTA5OnlineLua
          git pull
          
       - name: Echo json sha256
         id: build_sha
         run: |
          sha256sum GTA5OnlineLua/Release/Kiddion.json > sha256.checksum
          echo "build_sha=$(cat sha256.checksum)" >> $GITHUB_OUTPUT
          cat sha256.checksum
          
       - name: Echo yim sha256
         id: build_sha1
         run: |
          sha256sum GTA5OnlineLua/Release/YimMenu.json > sha256.checksum1
          echo "build_sha1=$(cat sha256.checksum1)" >> $GITHUB_OUTPUT
          cat sha256.checksum1
          
       - name: Create Release
         uses: softprops/action-gh-release@v1
         with:
          name: update
          tag_name: update
          body: |
            **This release has been built by Github Actions**
            Kid Hash:
            ```
            ${{ steps.build_sha.outputs.build_sha }}
            ```
            Yim Hash:
            ```
            ${{ steps.build_sha1.outputs.build_sha1 }}
            ```
          files: |
            GTA5OnlineLua/Release/Kiddion.json
            GTA5OnlineLua/Release/YimMenu.json
            
            
